### PR TITLE
AUR Package

### PR DESCRIPTION
**Pull request by justsaumit**
Allowing users to install the program directly from the AUR (Arch User Repository)

### CODE REVIEW

**Comment by justsaumit** [comment]
image

**Review by nexxeln — COMMENTED** [review]
This is great thanks!

Can we also do this for apt?

**Comment by nexxeln** [comment]
> This is great thanks!
> 
> Can we also do this for apt?

Actually I think this doesn't need to block this PR. Thanks so much!

**Comment by justsaumit** [comment]
> This is great thanks!
> 
> Can we also do this for apt?

Not really my expertise but I would love to try.

It's easy to put a package in the AUR because it is maintained by the users. 
However to add your package in the apt or even [Arch's official repositories](https://wiki.archlinux.org/title/official_repositories) (which allows one to install the package using the default package manager - pacman...yay is like a superset of community+aur packages)
requires some guidelines. 

From what I have gathered:
Firstly need to Package the program in deb format, that's easy.
Then we need to make sure we follow the DSFG(Debian Free Software Guidelines)
https://www.debian.org/doc/manuals/distribute-deb/distribute-deb.html#dfsg
Filing an ITP then Getting a Sponsor and Uploading and so on.

OR 
one can host their own repository with the deb package
https://wiki.debian.org/DebianRepository/Setup?action=show&redirect=HowToSetupADebianRepository
and encourage the users to add this repo to their `sources.list` https://www.debian.org/doc/manuals/distribute-deb/distribute-deb.html#package-repository

Really great and simple project :) wish to see this be ported to many other packages like deb, rpm, homebrew and so on.

**Comment by nexxeln** [comment]
> 

Yeah I would love to put it on homebrew, etc. I have just been lazy to do it and busy with other things.

**Pull request merged**
