### PR TITLE
fix: get current year

### PR DESCRIPTION
**Pull request by s10az**
Right now the default year will be 2022 since it is hard coded to it. It would be nice to change the default year according to the year right now since most people will use current year for creating new license.

I added `chrono` crate for getting current year. I also changed function name `get_current_year` to `get_year` since it will not return `current_year` which is a variable I added.

### CODE REVIEW

**Comment by nexxeln** [comment]
Hi! Sorry I missed this PR. 

Thank you for the contribution, happy to merge this, is there any reason you closed it?

**Comment by s10az** [comment]
I assumed that there were some particular reason you chose 2022 as default.

Anyway, I will reopen it.

**Review by nexxeln — APPROVED** [review]
Thank you!

**Comment by nexxeln** [comment]
I'll make a release in 2-3 days when I find free time.

**Comment by justsaumit** [comment]
@nexxeln bump to make a release for this and subsequent versions when you get time!

**Pull request merged**
